---
swagger: '2.0'
info:
  title: API de paginação
  version: 0.0.1
  description: |
    API para o desafio técnico da Raro Labs
    Aplicante: Roberval Filho

    Desafio: Construcão de uma API paginadora 
    Instruções: https://git.rarolabs.com.br/-/snippets/308
    
    Email: rslfilho@gmail.com
    Github: https://github.com/rslfilho
    LinkedIn: https://www.linkedin.com/in/rslfilho/

    Data: 05/02/2022
basePath: /v1
paths:
  /paginacao:
    get:
      tags:
        - Paginação
      summary: "Rota de paginação"
      description: Recebe as informações da paginação a partir da url, confere a validade das mesmas e, em caso de informações válidas, gera um array de paginação
      parameters:
        - in: query
          name: paginaAtual
          type: integer
          description: O número da página atual na paginação (precisa ser menor que "quantidadePaginas")
        - in: query
          name: quantidadePaginas
          type: integer
          description: O número total de páginas da paginação
      produces:
        - application/json
      responses:
        200:
          description: Retorna no corpo da resposta o id e um array com a paginação
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
                description: O id do usuário.
              paginacao:
                type: array
                items:
                  type: string
                description: Item da paginação.
        400:
          description: Parâmetros query não enviados, inválidos ou com "paginaAtual" maior que "quantidadePaginas"
          schema:
            type: object
            properties:
              message:
                type: string
                description: A mensagem de erro
        500:
          description: Erro interno do servidor
          schema:
            type: object
            properties:
              message:
                type: string
                description: A mensagem de erro